# Generated by Django 4.0.4 on 2022-07-08 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('photo', models.ImageField(null=True, upload_to='static')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('categories', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('destinationId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=500)),
                ('name', models.CharField(max_length=150)),
                ('longitude', models.CharField(max_length=250)),
                ('latitude', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('imageurl', models.URLField()),
                ('url', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=3)),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TourApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('hotelId', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=500)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(default='', max_length=250)),
                ('city', models.CharField(default='', max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('imageurl', models.URLField()),
                ('url', models.CharField(default='', max_length=100)),
                ('rating', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('state', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('user_profile', models.URLField()),
                ('testimony', models.CharField(max_length=600)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=250)),
                ('photo', models.ImageField(null=True, upload_to='static')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tourguide',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('languages', models.CharField(max_length=250)),
                ('photo', models.ImageField(null=True, upload_to='static')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='speciality', to='TourApp.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status', to='TourApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Park_bookings',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('bill', models.PositiveIntegerField()),
                ('destinationId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TourApp.destinations')),
                ('tourguideId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TourApp.tourguide')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels_bookings',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(default=django.utils.timezone.now)),
                ('bill', models.PositiveIntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TourApp.hotels')),
                ('tourguideId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='TourApp.tourguide')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TourApp.hotels')),
                ('park', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='TourApp.destinations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cart',
                'verbose_name_plural': 'carts',
            },
        ),
    ]
