# Generated by Django 4.0.4 on 2022-07-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0002_alter_hotels_bookings_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels_bookings',
            name='to_date',
            field=models.DateField(),
        ),
    ]
